#-*- encoding: utf-8 -*-
#
#MathSpeak localization for Traditional Chinese
#
#This file is covered by the GNU General Public License.
#See the file COPYING for more details.
#Copyright 2012-2013 World Light Information Limited and Hong Kong Blind Union.


from . import _core


_core.VARIANT_DICT.update({
	u"bold":        {None:u"粗體"},
	u"italic":      {None:u"斜體"},
	u"bold-italic": {None:u"粗斜體"},
	u"fraktur":     {None:u"哥德體"},
	u"bold-fraktur":{None:u"粗哥德體"},
	})


_core.LABEL_DICT.update({
	u"number":     {None:u"數值"},
	u"row":        {None:u"行"},
	u"column":     {None:u"列"},
	u"error":      {None:u"錯誤"},
	u"capital":    {None:u"大楷"},
	u"capword":    {None:u"大楷詞語"},
	u"positive":   {None:u"正"},
	u"negative":   {None:u"負"},
	u"start":      {None:u"開始"},
	u"end":        {None:u"結束"},
	u"script":     {None:u"標"},
	u"scriptclose":{None:u"標"},
	u"scriptend":  {None:u"結束標示"},
	u"under":      {None:u"底"},
	u"over":       {None:u"頂"},
	u"above":      {None:u"頂部"},
	u"below":      {None:u"底部"},
	u"baseline":   {None:u"基線"},
	u"super":      {None:u"上"},
	u"sub":        {None:u"下"},
	u"string":     {None:u"字串"},
	u"blank":      {None:u"空白"},
	u"layout":     {None:u"佈局"},
	u"enlarged":   {None:u"擴大"},
	u"matrix":     {None:u"矩陣"},
	u"determinant":{None:u"行列式"},
	u"binomial":   {None:u"Binomial或矩陣"},
	u"choose":     {None:u"選"},
	u"absolute":   {None:u"絕對值"},
	u"modifying":  {None:u"更改"},
	u"each":       {None:u"每個"},
	u"with":       {None:u"標示"},
	u"by":         {None:u"乘"},
	u"point":      {None:u"點"},
	u"and":        {None:u"又"},
	u"..":         {None:u"兩點"},
	u"once":       {None:u"1"},
	u"twice":      {None:u"2"},
	u"fracnest":   {None:u"嵌套"},
	u"fracover":   {None:u"除"},
	u"frac":       {None:u"分數"},
	u"rootnest":   {None:u"嵌套"},
	u"rootindex":  {None:u"方根"},
	u"rootstart":  {None:u"開始方根"},
	u"rootend":    {None:u"結束方根"},
	u"squared":    {None:u"平方"},
	u"cubed":      {None:u"立方"},
	u"cancel":     {None:u"刪除"},
	u"cancelwith": {None:u"改為"},
	u"set":        {None:u"集合"},
	})


_core.IDENTIFIER_DICT.update({
	u"\u221e":{None:u"無限"},
	u"lim":    {None:u"極限"},
	u"ln":     {None:u"自然對數"},
	u"log":    {None:u"對數"},
	u"sin":    {None:u"正弦"},
	u"cos":    {None:u"餘弦"},
	u"tan":    {None:u"正切"},
	u"cot":    {None:u"餘切"},
	u"sec":    {None:u"正割"},
	u"csc":    {None:u"餘割"},
	u"asin":   {None:u"反正弦"},
	u"acos":   {None:u"反餘弦"},
	u"atan":   {None:u"反正切"},
	u"acot":   {None:u"反餘切"},
	u"asec":   {None:u"反正割"},
	u"acsc":   {None:u"反餘割"},
	u"arcsin": {None:u"反正弦"},
	u"arccos": {None:u"反餘弦"},
	u"arctan": {None:u"反正切"},
	u"arccot": {None:u"反餘切"},
	u"arcsec": {None:u"反正割"},
	u"arccsc": {None:u"反餘割"},
	})


_core.OPERATOR_DICT.update({
	u"=":      {None:u"等於"},
	u",":      {None:u"逗號"},
	u".":      {None:u"句號"},
	u":":      {None:u"冒號"},
	u";":      {None:u"分號"},
	u"+":      {None:u"加"},
	u"-":      {None:u"減"},
	u"#":      {None:u"井號"},
	u"$":      {None:u"錢號"},
	u"<":      {None:u"細於"},
	u">":      {None:u"大於"},
	u"~":      {None:u"波浪線"},
	u"^":      {None:u"帽"},
	u"_":      {None:u"底線"},
	u"|":      {None:u"垂直線"},
	u"{":      {None:u"左大括號"},
	u"}":      {None:u"右大括號"},
	u"[":      {None:u"左方括號"},
	u"]":      {None:u"右方括號"},
	u"(":      {None:u"左括號"},
	u")":      {None:u"右括號"},
	u"\u00af":{None:u"伸展線"},
	u"\u00b1":{None:u"加或減"},
	u"\u00b7":{None:u"點"},
	u"\u00d7":{None:u"乘"},
	u"\u00f7":{None:u"除"},
	u"\u02d9":{None:u"點"},
	u"\u2016":{None:u"雙重垂直線"},
	u"\u2018":{None:u"開單括號"},
	u"\u2019":{None:u"關單括號"},
	u"\u201c":{None:u"開雙括號"},
	u"\u201d":{None:u"關雙括號"},
	u"\u2026":{None:u"省略號"},
	u"\u2032":{None:u"prime"},
	u"\u2033":{None:u"雙重 prime"},
	u"\u2034":{None:u"三重 prime"},
	u"\u2038":{None:u"caret"},
	u"\u2044":{None:u"除數斜線"},
	u"\u2061":{None:u""},
	u"\u2062":{None:u"乘"},
	u"\u2063":{None:u"逗號"},
	u"\u2107":{None:u"歐拉常數"},
	u"\u210e":{None:u"普朗克常數"},
	u"\u210f":{None:u"約化普朗克常數"},
	u"\u2135":{None:u"alef 無限"},
	u"\u2190":{None:u"左箭頭"},
	u"\u2191":{None:u"上箭頭"},
	u"\u2192":{None:u"右箭頭"},
	u"\u2193":{None:u"下箭頭"},
	u"\u2200":{None:u"所有"},
	u"\u2201":{None:u"compliment"},
	u"\u2202":{None:u"偏微分"},
	u"\u2203":{None:u"存在"},
	u"\u2204":{None:u"不存在"},
	u"\u2206":{None:u"判別"},
	u"\u2207":{None:u"倒三角算子"},
	u"\u2208":{None:u"元素"},
	u"\u2209":{None:u"非元素"},
	u"\u220a":{None:u"元素"},
	u"\u220b":{None:u"包含成員"},
	u"\u220c":{None:u"不包含成員"},
	u"\u220d":{None:u"包含成員"},
	u"\u220e":{None:u"結束證明"},
	u"\u220f":{None:u"求積"},
	u"\u2210":{None:u"上積"},
	u"\u2211":{None:u"求和"},
	u"\u2212":{None:u"減"},
	u"\u2213":{None:u"減或加"},
	u"\u2214":{None:u"點加"},
	u"\u2215":{None:u"除"},
	u"\u2216":{None:u"減子集"},
	u"\u2217":{None:u"星號"},
	u"\u2218":{None:u"環形"},
	u"\u2219":{None:u"項目符號"},
	u"\u221a":{None:u"平方根"},
	u"\u221b":{None:u"立方根"},
	u"\u221c":{None:u"四次方根"},
	u"\u221d":{None:u"成正比"},
	u"\u221f":{None:u"直角"},
	u"\u2220":{None:u"角"},
	u"\u2221":{None:u"測量角"},
	u"\u2222":{None:u"球面角"},
	u"\u2223":{None:u"分隔"},
	u"\u2224":{None:u"不分隔"},
	u"\u2225":{None:u"平行"},
	u"\u2226":{None:u"非平行"},
	u"\u2227":{None:u"邏輯和"},
	u"\u2228":{None:u"邏輯或"},
	u"\u2229":{None:u"焦集"},
	u"\u222a":{None:u"聯集"},
	u"\u222b":{None:u"積分"},
	u"\u222c":{None:u"雙重積分"},
	u"\u222d":{None:u"三重積分"},
	u"\u222e":{None:u"線積分"},
	u"\u222f":{None:u"雙重線積分"},
	u"\u2230":{None:u"體積分"},
	u"\u2231":{None:u"順時針積分"},
	u"\u2232":{None:u"順時針線積分"},
	u"\u2233":{None:u"逆時針線積分"},
	u"\u2234":{None:u"所以"},
	u"\u2235":{None:u"因為"},
	u"\u2236":{None:u"比"},
	u"\u2237":{None:u"比例"},
	u"\u2238":{None:u"點減"},
	u"\u2239":{None:u"excess"},
	u"\u223a":{None:u"幾何成正比"},
	u"\u223b":{None:u"homothetic-to"},
	u"\u223c":{None:u"波浪號"},
	u"\u223d":{None:u"反向波浪號"},
	u"\u223e":{None:u"反向 s"},
	u"\u223f":{None:u"正弦波"},
	u"\u2241":{None:u"非波浪號"},
	u"\u2242":{None:u"減波浪號"},
	u"\u2243":{None:u"漸近相等"},
	u"\u2244":{None:u"非漸近相等"},
	u"\u2245":{None:u"大約等於"},
	u"\u2246":{None:u"大約但不等於"},
	u"\u2247":{None:u"非大約亦非等於"},
	u"\u2248":{None:u"幾乎等於"},
	u"\u2249":{None:u"不幾乎等於"},
	u"\u224a":{None:u"幾乎等於或等於"},
	u"\u224b":{None:u"三重波浪號"},
	u"\u224c":{None:u"全部等於"},
	u"\u224d":{None:u"相等"},
	u"\u224e":{None:u"幾何相等"},
	u"\u224f":{None:u"相差"},
	u"\u2250":{None:u"趨向極限"},
	u"\u2251":{None:u"幾何等於"},
	u"\u2252":{None:u"大約等於或是影像"},
	u"\u2253":{None:u"是影像或大約等於"},
	u"\u2254":{None:u"冒號等於"},
	u"\u2255":{None:u"等於冒號"},
	u"\u2257":{None:u"等於號內含圓圈"},
	u"\u2258":{None:u"對應"},
	u"\u2259":{None:u"估計"},
	u"\u225a":{None:u"等角"},
	u"\u225c":{None:u"三角洲等於"},
	u"\u225d":{None:u"根據定義等於"},
	u"\u225e":{None:u"測定方法"},
	u"\u225f":{None:u"問號等於"},
	u"\u2260":{None:u"不等於"},
	u"\u2261":{None:u"全等於"},
	u"\u2262":{None:u"不全等於"},
	u"\u2263":{None:u"嚴格相等"},
	u"\u2264":{None:u"小於或等於"},
	u"\u2265":{None:u"大於或等於"},
	u"\u2266":{None:u"less-than-over-equal-to"},
	u"\u2267":{None:u"greater-than-over-equal-to"},
	u"\u2268":{None:u"less-than-but-not-equals"},
	u"\u2269":{None:u"greater-than-but-not-equals"},
	u"\u226a":{None:u"much-less-than"},
	u"\u226b":{None:u"much-greater-than"},
	u"\u226c":{None:u"betweens"},
	u"\u226d":{None:u"not-equivalent-to"},
	u"\u226e":{None:u"not-less-than"},
	u"\u226f":{None:u"not-greater-than"},
	u"\u2270":{None:u"neither-less-than-or-equals"},
	u"\u2271":{None:u"neither-greater-than-or-equals"},
	u"\u2272":{None:u"less-than-or-equivalent-to"},
	u"\u2273":{None:u"greater-than-or-equivalent-to"},
	u"\u2274":{None:u"neither-less-than-nor-equivalent-to"},
	u"\u2275":{None:u"neither-greater-than-nor-equivalent-to"},
	u"\u2276":{None:u"less-than-or-greater-than"},
	u"\u2277":{None:u"greater-than-or-less-than"},
	u"\u2278":{None:u"neither-less-than-nor-greater-than"},
	u"\u2279":{None:u"neither-greater-than-nor-less-than"},
	u"\u227a":{None:u"precedes"},
	u"\u227b":{None:u"succeeds"},
	u"\u227c":{None:u"precedes-or-equals"},
	u"\u227d":{None:u"succeeds-or-equals"},
	u"\u227e":{None:u"precedes-or-equivalent-to"},
	u"\u227f":{None:u"succeeds-or-equivalent-to"},
	u"\u2282":{None:u"subset-of"},
	u"\u2283":{None:u"superset-of"},
	u"\u2284":{None:u"not-subset-of"},
	u"\u2285":{None:u"not-superset-of"},
	u"\u2286":{None:u"subset-of-or-equals"},
	u"\u2287":{None:u"superset-of-or-equals"},
	u"\u2288":{None:u"neither-subset-nor-equals"},
	u"\u2289":{None:u"neither-superset-nor-equals"},
	u"\u228a":{None:u"subset-of-but-not-equals"},
	u"\u228b":{None:u"superset-of-but-not-equals"},
	u"\u228c":{None:u"multiset"},
	u"\u228d":{None:u"multiset-multiply"},
	u"\u228e":{None:u"multiset-union"},
	u"\u228f":{None:u"square-image-of"},
	u"\u2290":{None:u"square-original-of"},
	u"\u2291":{None:u"square-image-of-or-equals"},
	u"\u2292":{None:u"square-original-of-or-equals"},
	u"\u2293":{None:u"square-cap"},
	u"\u2294":{None:u"square-cup"},
	u"\u229a":{None:u"circled-ring"},
	u"\u229b":{None:u"circled-asterisk"},
	u"\u229c":{None:u"circled-equals"},
	u"\u229d":{None:u"circled-dash"},
	u"\u22a2":{None:u"right-tack"},
	u"\u22a3":{None:u"left-tack"},
	u"\u22a4":{None:u"down-tack"},
	u"\u22a5":{None:u"up-tack"},
	u"\u22a6":{None:u"asserts"},
	u"\u22a7":{None:u"models"},
	u"\u22a8":{None:u"is-true"},
	u"\u22a9":{None:u"forces"},
	u"\u22aa":{None:u"triple-vertical-bar-right-turnstile"},
	u"\u22ab":{None:u"double-vertical-bar-right-turnstile"},
	u"\u22ac":{None:u"not-proves"},
	u"\u22ad":{None:u"not-true"},
	u"\u22ae":{None:u"not-forces"},
	u"\u22b0":{None:u"precedes-under-relation"},
	u"\u22b1":{None:u"succeeds-under-relation"},
	u"\u22b2":{None:u"normal-subgroup-of"},
	u"\u22b3":{None:u"contains-normal-subgroup"},
	u"\u22b4":{None:u"normal-subgroup-of-or-equals"},
	u"\u22b5":{None:u"contains-normal-subgroup-or-equals"},
	u"\u22b6":{None:u"original-of"},
	u"\u22b7":{None:u"image-of"},
	u"\u22b9":{None:u"hermitian-conjugate-matrix"},
	u"\u22ba":{None:u"intercalate"},
	u"\u22bb":{None:u"logical x-or"},
	u"\u22bc":{None:u"logical nand"},
	u"\u22bd":{None:u"logical nor"},
	u"\u22be":{None:u"right-angle-with-arc"},
	u"\u22bf":{None:u"right-triangle"},
	u"\u22c4":{None:u"diamond"},
	u"\u22c6":{None:u"star"},
	u"\u22c7":{None:u"divide-times"},
	u"\u22c8":{None:u"bow-tie"},
	u"\u22c9":{None:u"left-normal-factor-semidirect-product"},
	u"\u22ca":{None:u"right-normal-factor-semidirect-product"},
	u"\u22cb":{None:u"left-semidirect-product"},
	u"\u22cc":{None:u"right-semidirect-product"},
	u"\u22cd":{None:u"reversed-tilde-equals"},
	u"\u22ce":{None:u"curly-logical-or"},
	u"\u22cf":{None:u"curly-logical-and"},
	u"\u22d0":{None:u"double-subset"},
	u"\u22d1":{None:u"double-superset"},
	u"\u22d2":{None:u"double-intersection"},
	u"\u22d3":{None:u"double-union"},
	u"\u22d4":{None:u"pitch-fork"},
	u"\u22d5":{None:u"equals-and-parallel-to"},
	u"\u22d6":{None:u"dotted-less-than"},
	u"\u22d7":{None:u"dotted-greater-than"},
	u"\u22d8":{None:u"very-much-less-than"},
	u"\u22d9":{None:u"very-much-greater-than"},
	u"\u22da":{None:u"less-than-equals-or-greater-than"},
	u"\u22db":{None:u"greater-than-equals-or-less-than"},
	u"\u22dc":{None:u"equals-or-less-than"},
	u"\u22dd":{None:u"equals-or-greater-than"},
	u"\u22de":{None:u"equals-or-precedes"},
	u"\u22df":{None:u"equals-or-succeeds"},
	u"\u22e0":{None:u"not-precedes-or-equals"},
	u"\u22e1":{None:u"not-succeeds-or-equals"},
	u"\u22e2":{None:u"not-square-image-of-or-equals"},
	u"\u22e3":{None:u"not-square-original-of-or-equals"},
	u"\u22e4":{None:u"square-image-of-or-not-equals"},
	u"\u22e5":{None:u"square-original-of-or-not-equals"},
	u"\u22e6":{None:u"less-than-but-not-equivalent-to"},
	u"\u22e7":{None:u"greater-than-but-not-equivalent-to"},
	u"\u22e8":{None:u"precedes-but-not-equivalent-to"},
	u"\u22e9":{None:u"succeeds-but-not-equivalent-to"},
	u"\u22ea":{None:u"not-normal-subgroup-of"},
	u"\u22eb":{None:u"not-contains-normal-subgroup"},
	u"\u22ec":{None:u"neither-normal-subgroup-of-nor-equals"},
	u"\u22ed":{None:u"neither-contains-normal-subgroup-nor-equals"},
	u"\u22ee":{None:u"垂直省略號"},
	u"\u22ef":{None:u"省略號"},
	u"\u22f0":{None:u"右上斜省略號"},
	u"\u22f1":{None:u"右下斜省略號"},
	u"\u22f2":{None:u"element-of-with-long-horizontal-stroke"},
	u"\u22f3":{None:u"element-of-with-vertical-bar-at-end-of-horizontal-stroke"},
	u"\u22f4":{None:u"element-of-with-vertical-bar-at-end-of-horizontal-stroke"},
	u"\u22f5":{None:u"element-of-with-dot-above"},
	u"\u22f6":{None:u"element-of-with-over-bar"},
	u"\u22f7":{None:u"element-of-with-over-bar"},
	u"\u22f8":{None:u"element-of-with-under-bar"},
	u"\u22f9":{None:u"element-of-with-two-horizontal-strokes"},
	u"\u22fa":{None:u"contains-with-long-horizontal-stroke"},
	u"\u22fb":{None:u"contains-with-vertical-bar-at-end-of-horizontal-stroke"},
	u"\u22fc":{None:u"contains-with-vertical-bar-at-end-of-horizontal-stroke"},
	u"\u22fd":{None:u"contains-with-over-bar"},
	u"\u22fe":{None:u"contains-with-over-bar"},
	u"\u22ff":{None:u"bag-member"},
	u"\u2308":{None:u"左上捨入"},
	u"\u2309":{None:u"右上捨入"},
	u"\u230a":{None:u"左下捨入"},
	u"\u230b":{None:u"右下捨入"},
	u"\u25a0":{None:u"black-square"},
	u"\u25a1":{None:u"white-square"},
	u"\u25aa":{None:u"small-black-square"},
	u"\u25ab":{None:u"small-white-square"},
	u"\u25ac":{None:u"black-rectangle"},
	u"\u25ad":{None:u"white-rectangle"},
	u"\u25ae":{None:u"black-vertical-rectangle"},
	u"\u25af":{None:u"white-vertical-rectangle"},
	u"\u25b0":{None:u"black-parallelogram"},
	u"\u25b1":{None:u"white-parallelogram"},
	u"\u25b2":{None:u"black-point-up-triangle"},
	u"\u25b3":{None:u"white-point-up-triangle"},
	u"\u25b4":{None:u"small-black-point-up-triangle"},
	u"\u25b5":{None:u"small-white-point-up-triangle"},
	u"\u25b6":{None:u"black-point-right-triangle"},
	u"\u25b7":{None:u"white-point-right-triangle"},
	u"\u25b8":{None:u"small-black-point-right-triangle"},
	u"\u25b9":{None:u"small-white-point-right-triangle"},
	u"\u25bc":{None:u"black-point-down-triangle"},
	u"\u25bd":{None:u"white-point-down-triangle"},
	u"\u25be":{None:u"small-black-point-down-triangle"},
	u"\u25bf":{None:u"small-white-point-down-triangle"},
	u"\u25c0":{None:u"black-point-left-triangle"},
	u"\u25c1":{None:u"white-point-left-triangle"},
	u"\u25c2":{None:u"small-black-point-left-triangle"},
	u"\u25c3":{None:u"small-white-point-left-triangle"},
	u"\u25c4":{None:u"black-point-left-triangle"},
	u"\u25c5":{None:u"white-point-left-triangle"},
	u"\u25c6":{None:u"black-diamond"},
	u"\u25c7":{None:u"white-diamond"},
	u"\u25c8":{None:u"white-diamond-containing-black-diamond"},
	u"\u25c9":{None:u"fisheye"},
	u"\u25cc":{None:u"dotted-circle"},
	u"\u25cd":{None:u"circle-with-vertical-fill"},
	u"\u25ce":{None:u"bullseye"},
	u"\u25cf":{None:u"black-circle"},
	u"\u25d6":{None:u"left-half-black-circle"},
	u"\u25d7":{None:u"right-half-black-circle"},
	u"\u25e6":{None:u"white-bullet"},
	u"\u2758":{None:u"vertical-bar"},
	u"\u2772":{None:u"left-shell-bracket"},
	u"\u2773":{None:u"right-shell-bracket"},
	u"\u27e6":{None:u"left-bag-bracket"},
	u"\u27e7":{None:u"right-bag-bracket"},
	u"\u27e8":{None:u"left-angle-bracket"},
	u"\u27e9":{None:u"right-angle-bracket"},
	u"\u27ea":{None:u"left-double-angle-bracket"},
	u"\u27eb":{None:u"right-double-angle-bracket"},
	u"\u27ec":{None:u"left-white-shell-bracket"},
	u"\u27ed":{None:u"right-white-shell-bracket"},
	u"\u27ee":{None:u"left-flat-parenthesis"},
	u"\u27ef":{None:u"right-flat-parenthesis"},
	u"\u2980":{None:u"triple-vertical-lines"},
	u"\u2981":{None:u"spot"},
	u"\u2982":{None:u"type-colon"},
	u"\u2983":{None:u"left-white-curly-brace"},
	u"\u2984":{None:u"right-white-curly-brace"},
	u"\u2985":{None:u"left-white-parenthesis"},
	u"\u2986":{None:u"right-white-parenthesis"},
	u"\u2987":{None:u"left-image-bracket"},
	u"\u2988":{None:u"right-image-bracket"},
	u"\u2989":{None:u"left-binding-bracket"},
	u"\u298a":{None:u"right-binding-bracket"},
	u"\u298b":{None:u"left-underbar-bracket"},
	u"\u298c":{None:u"right-underbar-bracket"},
	u"\u298d":{None:u"left-top-tick-bracket"},
	u"\u298e":{None:u"right-bottom-tick-bracket"},
	u"\u298f":{None:u"left-bottom-tick-bracket"},
	u"\u2990":{None:u"right-top-tick-bracket"},
	u"\u2991":{None:u"left-dotted-angle-bracket"},
	u"\u2992":{None:u"right-dotted-angle-bracket"},
	u"\u2993":{None:u"left-arc-less-than-bracket"},
	u"\u2994":{None:u"right-arc-greater-than-bracket"},
	u"\u2995":{None:u"left-double-arc-greater-than-bracket"},
	u"\u2996":{None:u"right-double-arc-less-than-bracket"},
	u"\u2997":{None:u"left-black-shell-bracket"},
	u"\u2998":{None:u"right-black-shell-bracket"},
	u"\u29a0":{None:u"spherical-angle-open-left"},
	u"\u29a1":{None:u"spherical-angle-open-up"},
	u"\u29a2":{None:u"turned-angle"},
	u"\u29a3":{None:u"reversed-angle"},
	u"\u29a4":{None:u"angle-with-under-bar"},
	u"\u29a5":{None:u"reversed-angle-with-under-bar"},
	u"\u29a6":{None:u"oblique-angle-open-up"},
	u"\u29a7":{None:u"oblique-angle-open-down"},
	u"\u29a8":{None:u"measured-angle-with-arrow-point-up-right"},
	u"\u29a9":{None:u"measured-angle-with-arrow-point-up-left"},
	u"\u29aa":{None:u"measured-angle-with-arrow-point-down-right"},
	u"\u29ab":{None:u"measured-angle-with-arrow-point-down-left"},
	u"\u29ac":{None:u"measured-angle-with-arrow-point-right-up"},
	u"\u29ad":{None:u"measured-angle-with-arrow-point-left-up"},
	u"\u29ae":{None:u"measured-angle-with-arrow-point-right-down"},
	u"\u29af":{None:u"measured-angle-with-arrow-point-left-down"},
	u"\u29b0":{None:u"reversed-empty-set"},
	u"\u29b1":{None:u"empty-set-with-ovar-bar"},
	u"\u29b2":{None:u"empty-set-with-circle-above"},
	u"\u29b3":{None:u"empty-set-with-right-arrow-above"},
	u"\u29b4":{None:u"empty-set-with-left-arrow-above"},
	u"\u29b5":{None:u"circle-with-horizontal-bar"},
	u"\u29b6":{None:u"circle-with-vertical-bar"},
	u"\u29b7":{None:u"circled-parallel-sign"},
	u"\u29b8":{None:u"circled-reverse-solidus"},
	u"\u29b9":{None:u"circled-perpendicular"},
	u"\u29ba":{None:u"circled-up-tack"},
	u"\u29bb":{None:u"crossed-out-circle"},
	u"\u29bc":{None:u"circled-percentage"},
	u"\u29bd":{None:u"up-arrow-through-circle"},
	u"\u29be":{None:u"circled-white-bullet"},
	u"\u29bf":{None:u"circled-bullet"},
	u"\u29c0":{None:u"circled-less-than"},
	u"\u29c1":{None:u"circled-greater-than"},
	u"\u29c2":{None:u"circle-with-small-cricle-to-the-right"},
	u"\u29c3":{None:u"circle-with-equal-sign-to-the-right"},
	u"\u29c4":{None:u"squared-up-diagonal-slash"},
	u"\u29c5":{None:u"squared-down-diagonal-slash"},
	u"\u29c6":{None:u"squared-asterisk"},
	u"\u29c7":{None:u"squared-small-circle"},
	u"\u29c8":{None:u"squared-square"},
	u"\u29c9":{None:u"two-joined-squares"},
	u"\u29ca":{None:u"triangle-with-dot-above"},
	u"\u29cb":{None:u"triangle-with-under-bar"},
	u"\u29cc":{None:u"s-in-triangle"},
	u"\u29cd":{None:u"triangle-with-serifs-at-bottom"},
	u"\u29ce":{None:u"right-triangle-above-left-triangle"},
	u"\u29cf":{None:u"left-triangle-beside-vertical-bar"},
	u"\u29d0":{None:u"vertical-bar-beside-right-triangle"},
	u"\u29d1":{None:u"bow-tie-with-left-half-black"},
	u"\u29d2":{None:u"bow-tie-with-right-half-black"},
	u"\u29d3":{None:u"black-bow-tie"},
	u"\u29d4":{None:u"times-with-left-half-black"},
	u"\u29d5":{None:u"times-with-right-half-black"},
	u"\u29d6":{None:u"white-hourglass"},
	u"\u29d7":{None:u"black-hourglass"},
	u"\u29d8":{None:u"left-wiggly-fence"},
	u"\u29d9":{None:u"right-wiggly-fence"},
	u"\u29da":{None:u"left-double-wiggly-fence"},
	u"\u29db":{None:u"right-double-wiggly-fence"},
	u"\u29dc":{None:u"incomplete-infinity"},
	u"\u29dd":{None:u"tie-over-infinity"},
	u"\u29de":{None:u"infinity-negated-with-vertical-bar"},
	u"\u29e0":{None:u"square-with-contoured-outline"},
	u"\u29e1":{None:u"increases-as"},
	u"\u29e2":{None:u"shuffle-product"},
	u"\u29e3":{None:u"equals-and-slanted-parallel"},
	u"\u29e4":{None:u"equals-and-slanted-parallel-over-tilde"},
	u"\u29e5":{None:u"identical-to-and-slanted-parallel"},
	u"\u29e6":{None:u"tautologically-equals"},
	u"\u29e7":{None:u"thermodynamic"},
	u"\u29e8":{None:u"down-triangle-with-left-half-black"},
	u"\u29e9":{None:u"down-triangle-with-right-half-black"},
	u"\u29ea":{None:u"black-diamond-with-down-arrow"},
	u"\u29eb":{None:u"black-lozenge"},
	u"\u29ec":{None:u"white-circle-with-down-arrow"},
	u"\u29ed":{None:u"black-circle-with-down-arrow"},
	u"\u29ee":{None:u"error-barred-white-square"},
	u"\u29ef":{None:u"error-barred-black-square"},
	u"\u29f0":{None:u"error-barred-white-diamond"},
	u"\u29f1":{None:u"error-barred-black-diamond"},
	u"\u29f2":{None:u"error-barred-white-circle"},
	u"\u29f3":{None:u"error-barred-black-circle"},
	u"\u29f5":{None:u"reverse-solidus"},
	u"\u29f6":{None:u"solidus-with-over-bar"},
	u"\u29f7":{None:u"reverse-solidus-with-horizontal-stroke"},
	u"\u29f8":{None:u"big-solidus"},
	u"\u29f9":{None:u"big-reverse-solidus"},
	u"\u29fa":{None:u"double-plus"},
	u"\u29fb":{None:u"triple-plus"},
	u"\u29fc":{None:u"left-curved-angle-bracket"},
	u"\u29fd":{None:u"right-curved-angle-bracket"},
	u"\u29fe":{None:u"tiny"},
	u"\u29ff":{None:u"miny"},
	u"\u2a1d":{None:u"join"},
	u"\u2a1e":{None:u"large-left-triangle"},
	u"\u2a1f":{None:u"schema-composition"},
	u"\u2a20":{None:u"schema-piping"},
	u"\u2a21":{None:u"schema-projection"},
	u"\u2a22":{None:u"plus-with-circle-above"},
	u"\u2a23":{None:u"plus-with-hat-above"},
	u"\u2a24":{None:u"plus-with-tilde-above"},
	u"\u2a25":{None:u"plus-with-dot-below"},
	u"\u2a26":{None:u"plus-with-tilde-below"},
	u"\u2a27":{None:u"plus-with-subscript-two"},
	u"\u2a28":{None:u"plus-with-black-triangle"},
	u"\u2a29":{None:u"minus-with-comma-above"},
	u"\u2a2a":{None:u"minus-with-dot-below"},
	u"\u2a2b":{None:u"minus-with-falling-dots"},
	u"\u2a2c":{None:u"minus-with-rising-dots"},
	u"\u2a2d":{None:u"plus-in-left-half-circle"},
	u"\u2a2e":{None:u"plus-in-right-half-circle"},
	u"\u2a2f":{None:u"叉"},
	u"\u2a30":{None:u"times-with-dot-above"},
	u"\u2a31":{None:u"times-with-under-bar"},
	u"\u2a32":{None:u"semi-direct-product-with-bottom-closed"},
	u"\u2a33":{None:u"smash-product"},
	u"\u2a34":{None:u"times-in-left-half-circle"},
	u"\u2a35":{None:u"times-in-right-half-circle"},
	u"\u2a36":{None:u"circled-times-with-hat-above"},
	u"\u2a37":{None:u"times-in-double-circle"},
	u"\u2a38":{None:u"circled-division"},
	u"\u2a39":{None:u"plus-in-triangle"},
	u"\u2a3a":{None:u"minus-in-triangle"},
	u"\u2a3b":{None:u"times-in-triangle"},
	u"\u2a3c":{None:u"interior-product"},
	u"\u2a3d":{None:u"right-hand-interior-product"},
	u"\u2a3e":{None:u"relationl-composition"},
	u"\u2a40":{None:u"intersection-with-dot"},
	u"\u2a41":{None:u"union-with-minus"},
	u"\u2a42":{None:u"union-with-over-bar"},
	u"\u2a43":{None:u"intersection-with-over-bar"},
	u"\u2a44":{None:u"intersection-with-logical-and"},
	u"\u2a45":{None:u"union-with-logical-or"},
	u"\u2a46":{None:u"union-above-intersection"},
	u"\u2a47":{None:u"intersection-above-union"},
	u"\u2a48":{None:u"union-above-bar-above-intersection"},
	u"\u2a49":{None:u"intersection-above-bar-above-union"},
	u"\u2a4a":{None:u"union-beside-and-joined-with-union"},
	u"\u2a4b":{None:u"intersection-beside-and-joined-with-intersection"},
	u"\u2a4c":{None:u"closed-union-with-serifs"},
	u"\u2a4d":{None:u"closed-intersection-with-serifs"},
	u"\u2a4e":{None:u"double-square-intersection"},
	u"\u2a4f":{None:u"double-square-union"},
	u"\u2a50":{None:u"closed-union-with-serifs-and-smash-product"},
	u"\u2a51":{None:u"邏輯和與頂標點"},
	u"\u2a52":{None:u"邏輯或與頂標點"},
	u"\u2a53":{None:u"雙邏輯和"},
	u"\u2a54":{None:u"雙邏輯或"},
	u"\u2a55":{None:u"兩重疊邏輯和"},
	u"\u2a56":{None:u"兩重疊邏輯或"},
	u"\u2a57":{None:u"sloping-logical-or"},
	u"\u2a58":{None:u"sloping-logical-and"},
	u"\u2a59":{None:u"logical-or-overlapping-logical-and"},
	u"\u2a5a":{None:u"logical-and-with-middle-stem"},
	u"\u2a5b":{None:u"logical-or-with-middle-stem"},
	u"\u2a5c":{None:u"logical-and-with-horizontal-dash"},
	u"\u2a5d":{None:u"logical-or-with-horizontal-dash"},
	u"\u2a5e":{None:u"logical-and-with-double-over-bar"},
	u"\u2a5f":{None:u"logical-and-with-under-bar"},
	u"\u2a60":{None:u"logical-and-with-double-under-bar"},
	u"\u2a61":{None:u"small-v-with-under-bar"},
	u"\u2a62":{None:u"logical-or-with-double-over-bar"},
	u"\u2a63":{None:u"logical-or-with-double-under-bar"},
	u"\u2a64":{None:u"domain-antirestriction"},
	u"\u2a65":{None:u"range-antirestriction"},
	u"\u2a87":{None:u"less-than-and-single-line-not-equals"},
	u"\u2a88":{None:u"greater-than-and-single-line-not-equals"},
	u"\u2aaf":{None:u"precedes-above-single-line-equals"},
	u"\u2ab0":{None:u"succeeds-above-single-line-equals"},
	})


class MathSpeakNode(_core.MathSpeakNode):

	def __init__(self):
		_core.MathSpeakNode.__init__(self)

	def _ordinalAbbrev(self,idx):
		return u"第 "+str(idx)

	def _mergeNumericFraction(self):
		if not self[0]._isNumber():  return
		if not self[1]._isNumber():  return
		self.text=u" ".join((self[1].text,u"分",self[0].text))


class MathSpeak(_core.MathSpeak):

	locale=u"zh_TW"

	def __init__(self):
		_core.MathSpeak.__init__(self)

	def _createNode(self):
		return MathSpeakNode()


# vim: set tabstop=4 shiftwidth=4:
